# Generated by Django 4.0.4 on 2022-07-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalhost',
            name='project',
        ),
    ]
