# Generated by Django 4.0.4 on 2022-07-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_remove_globalhost_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalhost',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_test.project', verbose_name='项目'),
            preserve_default=False,
        ),
    ]
